spring:
  application:
    name: music

  datasource:
    url: jdbc:postgresql://localhost:5678/music-db
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true